export const NEOFETCH_ART = [
  "                   -`                ",
  "                  .o+`               ",
  "                 `ooo/               ",
  "                `+oooo:              ",
  "               `+oooooo:             ",
  "               -+oooooo+:            ",
  "             `/:-:++oooo+:           ",
  "            `/++++/+++++++:          ",
  "           `/++++++++++++++:         ",
  "          `/+++ooooooooooooo/`       ",
  "         ./ooosssso++osssssso+`      ",
  "        .oossssso-````/ossssss+`     ",
  "       -osssssso.      :ssssssso.    ",
  "      :osssssss/        osssso+++.   ",
  "     /ossssssss/        +ssssooo/-   ",
  "   `/ossssso+/:-        -:/+osssso+- ",
  "  `+sso+:-`                 `.-/+oso:",
  " `++:.                           `-/+/",
  " .`                                 `/",
]

export const ARCH_HISTORY = [
  "+----------------------------------------------------+",
  "|       HISTORY OF LINUX DISTRIBUTIONS               |",
  "+----------------------------------------------------+",
  "  1992 - First distros (MCC, TAMU)",
  "  1993 - Slackware, Debian, SuSE",
  "  1994 - Red Hat",
  "  2002 - Arch Linux (rolling release, KISS, pacman)",
  "  2004 - Ubuntu (Linux for human beings)",
  "  2006 - Linux Mint",
  "  TODAY - 600+ active distributions",
  "+----------------------------------------------------+",
]

export const ARCH_WIKI = [
  "+-----------------------------------------------+",
  "|                ARCH WIKI                      |",
  "+-----------------------------------------------+",
  "  The Arch Wiki is the gold standard of Linux",
  "  documentation, used even by non-Arch users.",
  "",
  "  Arch principles:",
  "    - Simplicity (KISS)",
  "    - User-centric",
  "    - Rolling release",
  "    - Pragmatism",
  "    - Versatility",
  "",
  "  Why people love Arch:",
  "    - Total control",
  "    - Bleeding edge packages",
  "    - The AUR (~80,000 packages)",
  "    - Excellent documentation",
  "+-----------------------------------------------+",
]

export const I3_KEYBINDS = [
  "i3 default keybindings (Mod = Super):",
  "",
  "  Mod+Enter      open terminal",
  "  Mod+d          run launcher (rofi/dmenu)",
  "  Mod+1..9       switch workspace",
  "  Mod+Shift+1..9 move window to workspace",
  "  Mod+h / v      horizontal / vertical split",
  "  Mod+Shift+q    kill focused window",
  "  Mod+f          toggle fullscreen",
  "  Mod+Shift+space   toggle floating",
  "  Mod+r          resize mode",
  "  Mod+Shift+e    exit i3",
]

export const I3_CONFIG = [
  "# ~/.config/i3/config",
  "# i3 config file (v4)",
  "",
  "set $mod Mod4",
  "font pango:JetBrainsMono Nerd Font 10",
  "",
  "# class                 border  bg      text    indicator child_border",
  "client.focused          #1793D1 #1793D1 #FFFFFF #2E9EF4   #1793D1",
  "client.unfocused        #222222 #222222 #888888 #292D2E   #222222",
  "",
  "bindsym $mod+Return exec alacritty",
  "bindsym $mod+d exec --no-startup-id rofi -show drun",
  "bindsym $mod+Shift+q kill",
  "",
  "# split orientation",
  "bindsym $mod+h split h",
  "bindsym $mod+v split v",
  "",
  "# workspaces",
  "bindsym $mod+1 workspace number 1",
  "bindsym $mod+2 workspace number 2",
  "bindsym $mod+3 workspace number 3",
  "",
  "bar {",
  "    status_command i3blocks",
  "    position bottom",
  "    colors {",
  "        background #1A1A2E",
  "        focused_workspace  #1793D1 #1793D1 #FFFFFF",
  "    }",
  "}",
]

export const HELP_TEXT = [
  "Available commands:",
  "  ls cd pwd cat echo whoami id uname uptime",
  "  pacman -Syu / -Ss / -S / -Q / -R     package mgmt",
  "  yay -Ss <pkg>                        AUR helper",
  "  neofetch / fastfetch                 system info",
  "  btw / wiki / history                 lore",
  "  i3 keybindings                       help",
  "  clear / exit",
]
