export const HISTORY_TEXT = [
  "",
  "+----------------------------------------------------------+",
  "|        THE HISTORY OF CP/M (1974)                        |",
  "+----------------------------------------------------------+",
  "  CP/M was created by Gary Kildall at Digital Research",
  "  in 1974. It became the standard OS for microcomputers.",
  "",
  "  KEY FACTS",
  "  ------------------------------------------------",
  "  - First commercial micro OS",
  "  - Ran on Intel 8080/8085 and Zilog Z80",
  "  - Introduced 8.3 filenames",
  "  - A: B: C: drive letters started here",
  "  - Over 3000 software packages",
  "",
  "  THE IBM PC STORY",
  "  ------------------------------------------------",
  "  In 1980 IBM came to Digital Research for CP/M.",
  "  The meeting failed; IBM turned to Microsoft, who",
  "  bought QDOS (a CP/M clone), renamed it MS-DOS,",
  "  and licensed it to IBM. The rest is history.",
  "",
  "  LEGACY",
  "  ------------------------------------------------",
  "  - MS-DOS borrowed CP/M's design",
  "  - Drive letters survive to this day",
  "  - .COM/.EXE extensions trace back to CP/M",
  "+----------------------------------------------------------+",
  "",
]

export const HELP_TEXT = [
  "",
  "CP/M 2.2 BUILT-IN COMMANDS",
  "",
  "  DIR [D:]      LIST FILES ON DRIVE",
  "  TYPE FILE     DISPLAY FILE",
  "  ERA FILE      ERASE FILE",
  "  REN NEW=OLD   RENAME FILE",
  "  USER N        CHANGE USER 0-15",
  "  A: / B:       SWITCH DRIVE",
  "  STAT          DISK STATISTICS",
  "  HISTORY       CP/M HISTORY",
  "",
  "TRANSIENT PROGRAMS",
  "  PIP DEST=SRC  COPY FILES",
  "  ED FILE       LINE EDITOR",
  "  WS [FILE]     WORDSTAR EDITOR",
  "  MBASIC        MICROSOFT BASIC",
  "  ASM FILE      8080 ASSEMBLER",
  "  DDT           DEBUGGER",
  "",
]
