export const HELP_TEXT = [
  "",
  "APPLESOFT BASIC COMMANDS",
  "",
  "  PRINT TEXT      DISPLAY TEXT",
  "  LIST            LIST PROGRAM",
  "  RUN             RUN PROGRAM",
  "  NEW             ERASE PROGRAM",
  "  HOME            CLEAR SCREEN",
  "",
  "  GR              ENTER LORES (40X48 16-COLOR)",
  "  HGR             ENTER HIRES (280X192)",
  "  TEXT            BACK TO TEXT MODE",
  "  COLOR= N        SET LORES COLOR (0-15)",
  "  HCOLOR= N       SET HIRES COLOR (0-5)",
  "  PLOT X,Y        PLOT LORES PIXEL",
  "  HLIN X1,X2 AT Y HORIZONTAL LINE",
  "  VLIN Y1,Y2 AT X VERTICAL LINE",
  "  HPLOT X,Y       HIRES POINT",
  "  HPLOT X1,Y1 TO X2,Y2  HIRES LINE",
  "",
  "  CATALOG         LIST DOS FILES",
  "  LOAD NAME       LOAD PROGRAM",
  "  SAVE NAME       SAVE PROGRAM",
  "  PR#6            BOOT DOS 3.3",
  "  GAMES           CLASSIC GAME LIST",
  "  HISTORY         APPLE II HISTORY",
  "  EXIT            BACK TO MENU",
  "",
]

export const GAMES_TEXT = [
  "",
  "+------------------------------------+",
  "|     CLASSIC APPLE II GAMES         |",
  "+------------------------------------+",
  "  OREGON TRAIL (1971/1985)",
  "  KARATEKA (1984)",
  "  LODE RUNNER (1983)",
  "  PRINCE OF PERSIA (1989)",
  "  ULTIMA SERIES (1981+)",
  "  CHOPLIFTER (1982)",
  "  MYSTERY HOUSE (1980)",
  "  CASTLE WOLFENSTEIN (1981)",
  "+------------------------------------+",
  "",
]

export const HISTORY_TEXT = [
  "",
  "+----------------------------------------+",
  "|   THE HISTORY OF APPLE II (1977)       |",
  "+----------------------------------------+",
  "  DESIGNED BY STEVE WOZNIAK,",
  "  MARKETED BY STEVE JOBS.",
  "",
  "  - FIRST PC WITH COLOR GRAPHICS",
  "  - OPEN ARCHITECTURE",
  "  - INTEGRATED KEYBOARD",
  "  - BASIC IN ROM",
  "  - DISK II (1978)",
  "",
  "  VISICALC (1979) BECAME THE FIRST",
  "  KILLER APP THAT DROVE BUSINESS PCS.",
  "",
  "  6+ MILLION SOLD, PRODUCED 1977-1993.",
  "+----------------------------------------+",
  "",
]
