export const HISTORY_TEXT = [
  "",
  "=== HISTORIA DE BSD (Berkeley Software Distribution) ===",
  "",
  "BSD es una familia de sistemas operativos derivados de UNIX,",
  "desarrollados en la Universidad de California, Berkeley.",
  "",
  "ORIGENES (1977-1979):",
  "  1BSD (1977) - Primera distribucion por Bill Joy",
  "  2BSD (1978) - Introdujo vi, csh",
  "  3BSD (1979) - Primera version con memoria virtual",
  "",
  "ERA DARPA (1980-1983):",
  "  4BSD  (1980) - Base para TCP/IP",
  "  4.1BSD (1981) - Mejoras de rendimiento",
  "  4.2BSD (1983) - TCP/IP completo, sockets API",
  "",
  "4.3BSD (1986) - ESTA VERSION",
  "  Mejoras de red y rendimiento.",
  "",
  "CONTRIBUCIONES CLAVE:",
  "  - vi editor (Bill Joy)",
  "  - C Shell (csh) con history",
  "  - TCP/IP stack (la base de Internet)",
  "  - Sockets API",
  "  - Fast File System (FFS)",
  "",
  "LEGADO:",
  "  FreeBSD, OpenBSD, NetBSD",
  "  macOS / Darwin (basado en FreeBSD)",
  "  PlayStation OS (FreeBSD)",
  "  Nintendo Switch (FreeBSD)",
  "  Netflix CDN (FreeBSD)",
  "",
  "Sin BSD, no existiria Internet como la conocemos.",
  "",
]

export const HELP_TEXT = [
  "4.3 BSD UNIX - Available commands:",
  "  ls cd pwd cat man echo grep wc",
  "  vi <file>     visual editor (Bill Joy's vi)",
  "  who finger    user info",
  "  ps uptime     processes / load",
  "  uname -a      system info",
  "  ifconfig      network interfaces",
  "  ping <host>   ICMP echo",
  "  mail          read mailbox",
  "  su <user>     switch user (joy, ken, dmr, root)",
  "  history       4.3BSD history",
  "  clear / exit",
  "Try: man vi, man csh, man ls, man socket",
]

export const FINGER_DETAILS: Record<string, string[]> = {
  joy: [
    "Login: joy                            Name: Bill Joy",
    "Directory: /home/joy                  Shell: /bin/csh",
    "Office: Evans Hall, UC Berkeley",
    "Plan:",
    "  Author of vi, csh, and the BSD networking code.",
    "  Co-founder of Sun Microsystems.",
  ],
  ken: [
    "Login: ken                            Name: Ken Thompson",
    "Directory: /home/ken                  Shell: /bin/sh",
    "Office: Bell Labs, Murray Hill",
    "Plan:",
    "  Co-creator of UNIX, B language, and Plan 9.",
  ],
  dmr: [
    "Login: dmr                            Name: Dennis Ritchie",
    "Directory: /home/dmr                  Shell: /bin/sh",
    "Office: Bell Labs, Murray Hill",
    "Plan:",
    "  Inventor of the C language and co-creator of UNIX.",
  ],
}
