export const HISTORY_TEXT = [
  "",
  "+----------------------------------------------------------------+",
  "|              THE HISTORY OF UNIX (1969)                        |",
  "+----------------------------------------------------------------+",
  "  UNIX was born at Bell Labs in 1969 when Ken Thompson,",
  "  working on a discarded PDP-7, wrote a small operating system",
  "  to run his game 'Space Travel'.",
  "",
  "  Dennis Ritchie joined and they invented the C language to",
  "  rewrite the kernel - making UNIX portable across hardware.",
  "",
  "  KEY MILESTONES",
  "  ------------------------------------------------",
  "  1969 - First version (assembly, PDP-7)",
  "  1971 - 1st Edition Programmer's Manual",
  "  1973 - Rewritten in C (revolutionary)",
  "  1975 - V6 released to universities",
  "  1979 - V7 'ancestral UNIX'",
  "  1983 - System V released commercially",
  "",
  "  PHILOSOPHY",
  "  ------------------------------------------------",
  "  - Do one thing and do it well",
  "  - Write programs that work together",
  "  - Everything is a file",
  "  - Text streams are the universal interface",
  "",
  "  Without UNIX there would be no Linux, BSD, macOS, iOS or Android.",
  "+----------------------------------------------------------------+",
  "",
]

export const HELP_TEXT = [
  "UNIX V7 - Available commands:",
  "  ls [-la] [dir]   list directory",
  "  cd [dir]         change directory",
  "  pwd              print working directory",
  "  cat <file>       show file",
  "  ed <file>        edit file (line editor)",
  "  mkdir <dir>      make directory",
  "  rm <file>        remove file",
  "  cp <a> <b>       copy file",
  "  mv <a> <b>       rename file",
  "  echo <text>      print text",
  "  grep <pat> <f>   search pattern",
  "  wc <file>        word count",
  "  who              who is logged in",
  "  whoami / id      current user",
  "  ps / uptime      processes / load",
  "  date / uname     system info",
  "  su <user>        switch user (try ken, dmr, root)",
  "  man <cmd>        manual page",
  "  history          show UNIX history",
  "  clear / exit",
]
