export const HELP_TEXT = [
  "",
  "Comandos disponibles:",
  "  DIR [/W] [/P]   Lista archivos",
  "  CD [dir]        Cambia directorio",
  "  CD ..           Sube un nivel",
  "  MD <dir>        Crea directorio",
  "  RD <dir>        Elimina directorio",
  "  COPY <a> <b>    Copia archivo",
  "  DEL <file>      Elimina archivo",
  "  REN <a> <b>     Renombra archivo",
  "  TYPE <file>     Muestra archivo",
  "  EDIT [file]     Editor pantalla completa",
  "  TREE            Estructura de directorios",
  "  MEM             Memoria disponible",
  "  VER             Version de MS-DOS",
  "  DATE / TIME     Fecha y hora",
  "  CLS             Limpia pantalla",
  "  ECHO <texto>    Imprime texto",
  "  A: / C:         Cambia de unidad",
  "  SNAKE           Juega Snake",
  "  HISTORY         Historia de MS-DOS",
  "  EXIT            Volver al menu",
  "",
]

export const HISTORY_TEXT = [
  "",
  "+-----------------------------------+",
  "|     HISTORIA DE MS-DOS            |",
  "+-----------------------------------+",
  "  1981 Microsoft compra QDOS",
  "  1982 MS-DOS 1.25 - primera version",
  "  1983 MS-DOS 2.0 - disco duro",
  "  1984 MS-DOS 3.0 - 1.2MB floppy",
  "  1987 MS-DOS 3.3 - muy popular",
  "  1988 MS-DOS 4.0 - DOS Shell",
  "  1991 MS-DOS 5.0 - QBASIC, EDIT",
  "  1993 MS-DOS 6.0 - DoubleSpace",
  "  1994 MS-DOS 6.22 - ultima",
  "+-----------------------------------+",
  "",
]

export const MEM_TEXT = [
  "",
  "Memoria         Total       Usada       Libre",
  "----------     -------     -------     -------",
  "Convencional     640K         85K        555K",
  "Memoria alta     384K        128K        256K",
  "Memoria XMS    7,168K        512K      6,656K",
  "----------     -------     -------     -------",
  "Total memoria  8,192K        725K      7,467K",
  "",
]
